practiced javascript loops | James Roach
jamesroach7/c0121-code-solutions pull request #33
Opened 2021-01-29 02:03 UTC by jamesroach7

![Screen Shot 2021-01-28 at 6 03 19 PM](https://user-images.githubusercontent.com/76799878/106221787-1aa46400-6193-11eb-8d68-a1bed2e50267.png)
![Screen Shot 2021-01-28 at 6 03 24 PM](https://user-images.githubusercontent.com/76799878/106221795-1e37eb00-6193-11eb-95d1-99eeb555ca1a.png)

2021-01-29 21:31 UTC, thebearingedge requested changes

2021-01-29 21:31 UTC, thebearingedge commented on javascript-loops-practice/add-suffix-to-all.js
> +    withSuffix.push(words[i]);
It's best to avoid updating the input array (`words`) if you can.

```js
var withSuffix = words[i] + suffix;
```

2021-01-29 21:31 UTC, thebearingedge commented on javascript-loops-practice/filter-out-nulls.js
> +      i++;
Since `i++` appears in both logic branches, you can just put it after your `else`.

2021-01-29 21:31 UTC, thebearingedge commented on javascript-loops-practice/filter-out-strings.js
> +      i++;
Same here, regarding `i++`

2021-01-30 00:29 UTC, jamesroach7 commented on javascript-loops-practice/filter-out-nulls.js
> +      i++;
I put the i++ there in this case so that the while loop would skip over null values. Is there a way to tell an if statement to do nothing so that it skips over that code block and so the i++ can be moved?

2021-01-30 00:32 UTC, jamesroach7 commented on javascript-loops-practice/filter-out-nulls.js
> +      i++;
Actually never mind, I realized i can just use !== instead of ===

2021-01-30 00:39 UTC, thebearingedge approved these changes

2021-02-01 01:09 UTC, merged