completed string manipulation 1 | James Roach
jamesroach7/c0121-code-solutions pull request #37
Opened 2021-02-01 01:27 UTC by jamesroach7

![Screen Shot 2021-01-31 at 5 25 22 PM](https://user-images.githubusercontent.com/76799878/106405001-8f70db80-63e9-11eb-9387-fab567a48329.png)
![Screen Shot 2021-01-31 at 5 25 27 PM](https://user-images.githubusercontent.com/76799878/106405004-94358f80-63e9-11eb-9583-ee1699384b96.png)

2021-02-01 17:14 UTC, thebearingedge requested changes

2021-02-01 17:14 UTC, thebearingedge commented on string-manipulation-1/src/capitalize.js
> +      i++;
Since you are incrementing `i` in both the `if` and `else` blocks, just do it in one place.

```js
if (i === 0) {
  newWord += word[i].toUpperCase();
} else {
  newWord += word[i].toLowerCase();
}
i++;
```

2021-02-01 17:14 UTC, thebearingedge commented on string-manipulation-1/src/is-lower-cased.js
> +    }
You can simplify this a bit by flipping your comparison.
```js
if (word[i] !== word[i].toLowerCase()) {
  return false;
}
i++;
```

2021-02-01 17:14 UTC, thebearingedge commented on string-manipulation-1/src/is-upper-cased.js
> +    }
Same as above.

2021-02-01 17:14 UTC, thebearingedge commented on string-manipulation-1/src/is-vowel.js
> +    }
Since your `if` block has a `return` statement in it, you can leave out the `else`.

```js
if (vowels[i] === character) {
  return true;
}
i++;
```

2021-02-02 19:02 UTC, codingcodymiller approved these changes
🎉 🎉 🎉

2021-02-02 19:32 UTC, merged