created a modal | James Roach
jamesroach7/c0121-code-solutions pull request #44
Opened 2021-02-02 21:01 UTC by jamesroach7

![Screen Shot 2021-02-02 at 1 01 03 PM](https://user-images.githubusercontent.com/76799878/106661967-b00a7400-6556-11eb-966f-bd480f68f6ed.png)

2021-02-02 21:07 UTC, codingcodymiller requested changes
Hey James! Great work so far, one note for you:

2021-02-02 21:07 UTC, codingcodymiller commented on javascript-modal/styles.css
> +  bottom: 3rem;
You don't need to absolute position this.

2021-02-02 21:17 UTC, thebearingedge requested changes

2021-02-02 21:17 UTC, thebearingedge commented on javascript-modal/styles.css
> +  margin: 1rem 11rem;
If you put `text-align: center` on your dialog box (the white part), everything will be centered.

2021-02-03 00:24 UTC, codingcodymiller approved these changes
Nice work!! 🎉

2021-02-03 05:26 UTC, merged